name: Build node js application
on:
  workflow_dispatch: 

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo 
        uses: actions/checkout@v4

      - name: step up the nodejs  
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Compile the syntax check    
        run: |
          find . -name "*.js" -exec node --check {} +
          echo "Frontend JavaScript syntax check passed âœ…"
          
  gitleak-scan:
    runs-on: ubuntu-latest
    needs: compile
    continue-on-error: true
    steps:
      - name: Checkout the repo 
        uses: actions/checkout@v4
         
      - name: Scan the source code
        uses: gitleaks/gitleaks-action@v2

      - name: Run Aqua Build Security
        uses: aquasecurity/build-security-action@main  
